### ISSUE TITLE
Folder location for schematic files

### ISSUE THREAD

**Issue by Tavren** [Eco-Russian-Community/WorldEdit#2]
As @drkshrk mentioned at [TheKye/Eco-WorldEdit](https://github.com/TheKye/Eco-WorldEdit/issues/10)

> Does it make sense to move the "Schematics" folder from ../Schematics to ../Configs/Mods/WorldEdit/Schematics instead of the base directory like other mods so that hosting providers don't block access?
> @drkshrk

**Comment by StallEF** [comment]
Need change fplder place for new Mod system => \Mods\UserCode\WorldEdit\Schematics\

**Comment by Tavren** [comment]
Changed to SLG suggested location

**Comment by StallEF** [comment]
path for export save correct - \Mods\UserCode\WorldEdit\Schematics
