### ISSUE TITLE
Commands can change the impenetrable block causing bad things

### ISSUE THREAD

**Issue by Tavren** [Eco-Russian-Community/WorldEdit#3]
As @drkshrk mentioned at [TheKye/Eco-WorldEdit](https://github.com/TheKye/Eco-WorldEdit/issues/7)

> Impenetrable Stone Block can be removed with the wand causing weird things. The set command needs a safety in it that if this type of block is selected it doesn't let you change it.
> @drkshrk

**Comment by StallEF** [comment]
commands /set and /del not delete impenetrableblock more
