### ISSUE TITLE
Сompression of export files

### ISSUE THREAD

**Issue by StallEF** [Eco-Russian-Community/WorldEdit#9]
Objective: to study compression methods and choose the most suitable one for use on a game servers (minimum impact on the CPU)

**Comment by Tavren** [comment]
LZ4 - work with streams, as result we have compressed schematic file
Zip - as result we have zip with schematic file inside

My suggestion is LZ4 if use any

We should decide how we going use this.
1 - Just use compression on any schematic
2 - Add new command like `/exportzip` to create compressed file
3 - Config?

**Comment by StallEF** [comment]
in work: LZ4 compression on any schematic
